[project]
name = "pingv4_tourney"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "pingv4==0.1.1",
    "pygame>=2.6.1",
    "rich>=14.3.2",
    "tqdm>=4.67.3",
]
